### ISSUE TITLE
confusion about usage reversal astro in react

### ISSUE THREAD

**Issue by wassfila** [withastro/houston.astro.build#2]
question : can I use an Astro component from a react component ?

answer : Yes, you can use an Astro component from a React component.
Resources
[Framework Components: Using Framework Components](https://docs.astro.build/en/core-concepts/framework-components/#using-framework-components)
[Framework Components: Nesting Framework Components](https://docs.astro.build/en/core-concepts/framework-components/#nesting-framework-components)
[Framework Components: Mixing Frameworks](https://docs.astro.build/en/core-concepts/framework-components/#mixing-frameworks)
[Components](https://docs.astro.build/en/core-concepts/astro-components/)

**Comment by natemoo-re** [comment]
Thanks for the report! We just did some cleanup on the underlying data and it seems like this isn't a problem anymore!

<img width="647" alt="CleanShot 2023-01-28 at 16 18 24@2x" src="https://user-images.githubusercontent.com/7118177/215293624-36455c0e-8564-48b6-b25a-9b9fe887b7ea.png">
