### ISSUE TITLE
Text overflow

### ISSUE THREAD

**Issue by qw-in** [withastro/houston.astro.build#3]
Looks like long code blocks can overflow on mobile

![Screenshot_2023-01-27-17-57-38-36_3aea4af51f236e4932235fdada7d1643.jpg](https://user-images.githubusercontent.com/19194187/215236155-6cece37c-3bd8-4a99-9625-b913892b3782.jpg)

**Comment by natemoo-re** [comment]
Thanks, just pushed a fix for this!
