### ISSUE TITLE
Incorrect info about using custom tailwind base.css

### ISSUE THREAD

**Issue by will-lol** [withastro/houston.astro.build#4]
I asked "how can I set a custom tailwind base.css". Houston gave the following:
"You can use a custom tailwind base.css by setting the config.applyBaseStyles option to false and providing a custom path to a Tailwind config file using the config.path option."
The config.path option is to provide an alternate config, not an alternate base.css.

**Comment by natemoo-re** [comment]
Thanks for reporting! We just cleaned up the underlying data and it seems like the answer is much more accurate now!

<img width="653" alt="CleanShot 2023-01-28 at 16 19 30@2x" src="https://user-images.githubusercontent.com/7118177/215293668-a9d5133e-de4f-4a24-84b7-f17e81c30a45.png">
