### ISSUE TITLE
Commas (,) are added in the links in the Resources section of an answer.

### ISSUE THREAD

**Issue by DarthGigi** [withastro/houston.astro.build#5]
I noticed that when HoustonAI generates an answer, it adds commas (,) in the links (not all of them) in the Resources section of an answer:
![Screenshot](https://user-images.githubusercontent.com/47110839/215268146-e835b566-3883-4e1f-bfb5-e65c1540784a.png)

This causes the hyperlinks to not work correctly:

<details>
<summary>With a comma</summary>

![Screenshot](https://user-images.githubusercontent.com/47110839/215268274-483860fc-c9b5-43db-b38c-7dc050b0b6b2.png)

</details>

<details>
<summary>Without a comma</summary>

![Screenshot](https://user-images.githubusercontent.com/47110839/215268402-7bac2354-2f21-4925-afdf-9ece19c71ec9.png)

</details>

<details>
<summary>However, as you can see in the following screenshot, this is not always the case:</summary>

![Screenshot](https://user-images.githubusercontent.com/47110839/215268462-b24117cf-66f1-48c1-a284-6caef642f651.png)

Another example, in all of the following links shown in the screenshot a comma has been added:
![Screenshot](https://user-images.githubusercontent.com/47110839/215268619-30d6b6d4-8ddc-45c0-a125-b1c1f824f549.png)
</details>

**Comment by natemoo-re** [comment]
Thanks for the report! I pushed a fix to our backend, but will leave this open until we redploy

**Comment by natemoo-re** [comment]
This should be fixed and deployed now!
